### ISSUE TITLE
Feature request - dynamic schema name in safe mode

### ISSUE THREAD

**Issue by penx** [nearform/sql#40]
It would be useful to be able to use a dynamic schema name as follows:

```js
const sql = SQL`SELECT * FROM ${schema}.users WHERE user_id = ${userId}`
```

At the moment, this will fail (e.g. when used with node-postgres), as `schema` is turned in to a parameter in a prepared statement, and, from what I understand, postgres does not support variable schema names in prepared statements.

A workaround is to do this:

```js
const sql = SQL`SELECT * FROM `
sql.append(SQL`${schema}.users `, { unsafe: true })
sql.append(SQL`WHERE user_id = ${userId}`)
```

Switching in and out of unsafe mode is not ideal.

If it can be achieved without risk of introducing SQL injection vulnerabilities, it would be good if this library could handle it and convert:

```js
const schema = 'schema_name'
const userId = 1
const sql = SQL`SELECT * FROM ${schema}.users  WHERE user_id = ${userId}`
```

in to:

```js
{
  text: 'SELECT * FROM "schema_name".users WHERE user_id = ${1}',
  values: [1]
}
```
 
(note that `schema_name` can be wrapped with double quotes in the text, which may help to ensure no SQL injection vulnerabilities)

Alternatively, perhaps there is another way to achieve this, in which case it would be good to document it.

**Comment by mcollina** [comment]
This is hard on purpose, as it's `unsafe`. Wrapping in quotes needs to be done extremely carefully as that could be easily escaped. I recommend against implementing this.

**Comment by penx** [comment]
Sure I'm certainly against this if it can't be done in a way we are certain is safe. I thought perhaps there would be a safe way of doing this.

My main thinking with this is to prevent unsafe fatigue - if you have a code base that has a lot of code like the above and you become used to seeing `{ unsafe: true }` used everywhere, potentially missing somewhere where it's being used dangerously.

I think that, ideally, I'd want to send the schema to node-postgres in a config option (something like `db.query(sql, { schema })`), but perhaps there's good reason that doesn't exist either!

Slightly related issue, but for configuration - https://github.com/brianc/node-postgres/issues/1123

**Comment by paolochiodi** [comment]
The problem here is that `SQL` has no way to determine which placeholder should be quoted as a string literal (single quotes) and which one as an identifier (double quotes).

A way to implement something similar would be to have an utility function like `unsafe` that returns an object that would be understood by `SQL` as not to be quoted, resulting in something like

```js
SQL`SELECT * FROM ${unsafe(schema)}.users  WHERE user_id = ${userId}`
```

Even better, we could provide a function to properly quote a database identifier (schema, table and column names), something like:

```js
SQL`SELECT * FROM ${quoteIdent(schema)}.users  WHERE user_id = ${userId}`
```

Such a function would be useful in other context too (i.e. when dealing with camel case table names etc)

It would open a some security concern as an attacker may find a way to craft an input value that could be understood by `SQL` as a safe placeholder, mimicking the `unsafe` utility function.
This could probably be mitigate by using a symbol to tag the object.

**Comment by mcollina** [comment]
that would work @paolochiodi!

**Comment by simoneb** [comment]
If we implement this, we should make sure it works correctly across the various dialects supported by this library.

**Comment by simoneb** [comment]
@mcollina @paolochiodi can you please have a look at the linked PR to see if you agree with the approach?  

https://github.com/nearform/sql/pull/41
